/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import kotlinx.coroutines.flow.collect
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking

fun main(): Unit = runBlocking {
    val counter = Counter()

    launch {
        counter.count.collect { value ->
            println("Counter value is $value")
        }
    }
    counter.increment()
}